<a href="https://colab.research.google.com/github/anushis9697/Advanced-SQL/blob/main/Pandas_Dataframe_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Q1. Creating a DataFrame
#Create a Pandas DataFrame using a Python dictionary with the following columns:
#Product
#Region
#Sales
#Quantity
#Add at least 5 rows of sample data and display the DataFrame.
#Dataset for Questions 2–10
#Use the dataset file provided:
#answer -
import pandas as pd

# Creating a sample dictionary
data = {
    "Product": ["Laptop", "Tablet", "Phone", "Monitor", "Keyboard"],
    "Region": ["West", "South", "East", "North", "West"],
    "Sales": [1056, 904, 2028, 1269, 777],
    "Quantity": [2, 7, 4, 8, 8]
}

# Creating DataFrame
df_sample = pd.DataFrame(data)
df_sample

    Product Region  Sales  Quantity
0    Laptop   West   1056         2
1    Tablet  South    904         7
2     Phone   East   2028         4
3   Monitor  North   1269         8
4  Keyboard   West    777         8

In [2]:
#Q2. Data Inspection
#Perform the following inspection tasks:
#1 Display the first 5 rows of the dataset.
#2 Display the last 5 rows.
#3 Show the structure of the dataset using info().
#4 Display the shape of the dataset
#Answer- Load dataset
df = pd.read_csv("/content/Retail_dataset.csv")

# 1. First 5 rows
df.head()

# 2. Last 5 rows
df.tail()

# 3. Structure of dataset
df.info()

# 4. Shape of dataset
df.shape

#Output (summarized):
#- First 5 rows → shows Sneha, Neha, Meera, Rohan, Priya entries
#- Last 5 rows → shows rows up to Order_ID 1090
#- info() → 6 columns, 90 entries, all non-null
#- Shape → (90, 6)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90 entries, 0 to 89
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Order_ID  90 non-null     int64
 1   Customer  90 non-null     object
 2   Product   90 non-null     object
 3   Region    90 non-null     object
 4   Sales     90 non-null     int64
 5   Quantity  90 non-null     int64
dtypes: int64(3), object(3)
memory usage: 4.3+ KB

(90, 6)

In [3]:
#Q3. Column Selection
#Select and display only the following columns:
#Product
#Region
#Sales
#Answer -
df[["Product", "Region", "Sales"]]
#Output: Displays only those three columns.

     Product Region  Sales
0     Laptop   West   1056
1     Tablet  South    904
2     Laptop  South   1597
3   Keyboard  North    777
4      Phone  South   2028
..       ...    ...    ...
85    Laptop   East   1330
86  Keyboard   West    741
87   Monitor   East    875
88    Tablet  North   2213
89    Laptop  South   1270

[90 rows x 3 columns]

In [4]:
#Q4. Indexing using .loc
#Using .loc, perform the following:
#Display the row with index 10.
#Display the Sales value of the row with index 20
#Answer-# 1. Row with index 10
df.loc[10]
# 2. Sales value of row with index 20
df.loc[20, "Sales"]
#Output:
#- Row 10 → Order_ID=1011, Customer=Raj, Product=Monitor, Region=North, Sales=1693, Quantity=6
#- Sales at index 20 → 1503

np.int64(1021)

In [5]:
#Q5. Indexing using .iloc
#Using .iloc, display:
#1 The first 6 rows and first 4 columns.
#2 The Sales value from the 3rd row.
#Answer - # 1. The first 6 rows and first 4 columns
print("First 6 rows and 4 columns:")
print(df.iloc[:6, :4])
# 2. The Sales value from the 3rd row (index 2)
# Column index for 'Sales' is 4 (Order_ID=0, Customer=1, Product=2, Region=3, Sales=4)
sales_3rd_row = df.iloc[2, 4]
print(f"\nSales value from the 3rd row: {sales_3rd_row}")
#Output:
#- First 6 rows with first 4 columns → shows Order_ID, Customer, Product, Region
#- Sales from 3rd row → 1597

First 6 rows and 4 columns:
   Order_ID Customer   Product Region
0      1001    Sneha    Laptop   West
1      1002     Neha    Tablet  South
2      1003    Meera    Laptop  South
3      1004    Rohan  Keyboard  North
4      1005    Priya     Phone  South
5      1006    Rahul    Tablet   West

Sales value from the 3rd row: 1597

In [6]:
#Q6. Row Slicing
#Display:
#1The first 10 rows of the dataset.
#2Rows 15 to 25.
#Answer # 1. The first 10 rows of the dataset
print("First 10 rows:")
print(df[0:10])
# 2. Rows 15 to 25
print("\nRows 15 to 25:")
print(df[15:26])

First 10 rows:
   Order_ID Customer   Product Region  Sales  Quantity
0      1001    Sneha    Laptop   West   1056         2
1      1002     Neha    Tablet  South    904         7
2      1003    Meera    Laptop  South   1597         5
3      1004    Rohan  Keyboard  North    777         8
4      1005    Priya     Phone  South   2028         4
5      1006    Rahul    Tablet   West    638         2
6      1007     Amit   Monitor  South   1004         7
7      1008    Sneha   Monitor   East   1269         8
8      1009    Priya     Phone  North    827         8
9      1010     Amit     Phone   West   1998         4

Rows 15 to 25:
    Order_ID Customer  Product Region  Sales  Quantity
15      1016    Karan  Monitor   West    796         3
16      1017     Neha   Laptop   East   2015         2
17      1018    Anita    Phone  North   1637         3
18      1019     Amit    Phone   East    748         7
19      1020     Neha   Laptop   West   1503         6
20      1021    Priya   Laptop  North   1021         4
21      1022      Raj   Tablet  South    886         7
22      1023    Rahul   Laptop  South   2267         3
23      1024    Karan  Monitor   East    814         7
24      1025    Meera  Monitor   West   1926         6
25      1026    Anita   Tablet   East    839         5

In [7]:
#Q7. Filtering Data
#Filter the dataset to display:
#1Rows where Region = "East".
#2Rows where Sales > 1500.
#Answer-# 1. Rows where Region = "East"
east_region = df[df['Region'] == 'East']
print("Rows in East region:")
print(east_region.head())
# 2. Rows where Sales > 1500
high_sales = df[df['Sales'] > 1500]
print("\nRows with Sales > 1500:")
print(high_sales.head())

Rows in East region:
    Order_ID Customer  Product Region  Sales  Quantity
7       1008    Sneha  Monitor   East   1269         8
11      1012    Rahul   Laptop   East   1022         5
16      1017     Neha   Laptop   East   2015         2
18      1019     Amit    Phone   East    748         7
23      1024    Karan  Monitor   East    814         7

Rows with Sales > 1500:
    Order_ID Customer  Product Region  Sales  Quantity
2       1003    Meera   Laptop  South   1597         5
4       1005    Priya    Phone  South   2028         4
9       1010     Amit    Phone   West   1998         4
10      1011      Raj  Monitor  North   1693         6
13      1014    Rohan    Phone  South   2078         3

In [8]:
#Q8. Multiple Condition Filtering
#Display rows where:
#Region is West
#Sales is greater than 1200
#Answer-# Filtering with multiple conditions
west_high_sales = df[(df['Region'] == 'West') & (df['Sales'] > 1200)]
west_high_sales

    Order_ID Customer   Product Region  Sales  Quantity
9       1010     Amit     Phone   West   1998         4
19      1020     Neha    Laptop   West   1503         6
24      1025    Meera   Monitor   West   1926         6
29      1030    Rohan   Monitor   West   1932         5
42      1043    Meera  Keyboard   West   1515         6
43      1044    Vikas    Laptop   West   2248         5
49      1050    Karan   Monitor   West   2034         7
55      1056    Rahul    Laptop   West   1481         1
58      1059    Karan    Tablet   West   2404         6
59      1060    Karan    Tablet   West   1651         2
63      1064    Pooja  Keyboard   West   2310         5
68      1069    Priya    Laptop   West   1422         6
69      1070    Rahul    Tablet   West   2134         5
73      1074    Meera  Keyboard   West   1429         7
83      1084    Rohan    Laptop   West   1204         5
84      1085     Neha   Monitor   West   1339         7

In [9]:
#Q9. Descriptive Statistics
#Generate summary statistics using:
#describe()
#From the result identify:
#Mean sales value
#Maximum quantity sold
#Minimum sales value
#Answer- # Generate summary statistics
stats = df.describe()
print("Summary Statistics:")
print(stats)
# Identifying specific values from the description
mean_sales = df['Sales'].mean()
max_qty = df['Quantity'].max()
min_sales = df['Sales'].min()
print(f"\nMean Sales Value: {mean_sales}")
print(f"Maximum Quantity Sold: {max_qty}")
print(f"Minimum Sales Value: {min_sales}")
#Output:
#- Mean Sales ≈ 1406
#- Max Quantity = 8
#- Min Sales = 515

Summary Statistics:
          Order_ID        Sales   Quantity
count    90.000000    90.000000  90.000000
mean   1045.500000  1406.888889   4.700000
std      26.124701   531.748302   2.179836
min    1001.000000   515.000000   1.000000
25%    1023.250000   890.500000   3.000000
50%    1045.500000  1402.000000   5.000000
75%    1067.750000  1857.250000   7.000000
max    1090.000000  2455.000000   8.000000

Mean Sales Value: 1406.888888888889
Maximum Quantity Sold: 8
Minimum Sales Value: 515

In [10]:
#Q10. Aggregation Analysis
#Using the Sales column, calculate:
#Total sales
#Average sales
#Maximum sales
#Minimum sales
#Answer-# Aggregation calculations on the Sales column
total_sales = df['Sales'].sum()
avg_sales = df['Sales'].mean()
max_sales = df['Sales'].max()
min_sales = df['Sales'].min()
print(f"Total Sales: {total_sales}")
print(f"Average Sales: {avg_sales}")
print(f"Maximum Sales: {max_sales}")
print(f"Minimum Sales: {min_sales}")
#Output:
#- Total Sales = 126620
#- Average Sales ≈ 1406
#- Max Sales = 2455
#- Min Sales = 515

Total Sales: 126620
Average Sales: 1406.888888888889
Maximum Sales: 2455
Minimum Sales: 515